### ISSUE TITLE
Error while building minicap

### ISSUE THREAD

**Issue by RameshY703** [openstf/minicap#72]
I took following step to build minicap on ubuntu 15.04.Installed NDK-15.0.4075724,CMake and LLDB.
1.Git clone project
2.cd minicap
3.git submodule init
4.git submodule update
5.ndk-build

**I am getting following error during command ndk-build:**

Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-14.    
[armeabi-v7a] Gdbserver      : [arm-linux-androideabi-4.9] libs/armeabi-v7a/gdbserver
[armeabi-v7a] Gdbsetup       : libs/armeabi-v7a/gdb.setup
[arm64-v8a] Gdbserver      : [aarch64-linux-android-4.9] libs/arm64-v8a/gdbserver
[arm64-v8a] Gdbsetup       : libs/arm64-v8a/gdb.setup
[x86] Gdbserver      : [x86-4.9] libs/x86/gdbserver
[x86] Gdbsetup       : libs/x86/gdb.setup
[x86_64] Gdbserver      : [x86_64-4.9] libs/x86_64/gdbserver
[x86_64] Gdbsetup       : libs/x86_64/gdb.setup
[armeabi-v7a] Compile++ thumb: minicap-common <= SimpleServer.cpp
jni/minicap/SimpleServer.cpp: In destructor 'SimpleServer::~SimpleServer()':
jni/minicap/SimpleServer.cpp:14:5: error: '::close' has not been declared
     ::close(mFd);
     ^
jni/minicap/SimpleServer.cpp: In member function 'int SimpleServer::start(const char*)':
jni/minicap/SimpleServer.cpp:27:32: error: 'memset' was not declared in this scope
   memset(&addr, 0, sizeof(addr));
                                ^
jni/minicap/SimpleServer.cpp:29:55: error: 'strlen' was not declared in this scope
   strncpy(&addr.sun_path[1], sockname, strlen(sockname));
                                                       ^
jni/minicap/SimpleServer.cpp:29:56: error: 'strncpy' was not declared in this scope
   strncpy(&addr.sun_path[1], sockname, strlen(sockname));
                                                        ^
jni/minicap/SimpleServer.cpp:33:5: error: '::close' has not been declared
     ::close(sfd);
     ^
make: *** [obj/local/armeabi-v7a/objs-debug/minicap-common/SimpleServer.o] Error 1

**Comment by sorccu** [comment]
Duplicate of #71.

**Comment by RameshY703** [comment]
Thank you @Sorccu  for your instant reply.

**Comment by sorccu** [comment]
Should work now, however NDK 15 dropped support for Android 2.3.

**Comment by wangzirui** [comment]
It doesn't seem to be a problem of the NDK level. I set the level to 22 and still get the errors.

**Comment by wangzirui** [comment]
Adding #include <string.h> to SimpleServer.cpp solved the problems for me.

**Comment by sorccu** [comment]
Yep but that was a different issue.
