### ISSUE TITLE
Samsung Galaxy S5 Neo disconnects or seg faults.

### ISSUE THREAD

**Issue by Trugath** [openstf/minicap#8]
phone:

```
manufacturer: 'SAMSUNG'
model: 'SM-G903F'
version: '5.1.1'
abi: 'armeabi-v7a'
sdk: '22'
product: 's5neoltexx'
```

When using STF, if the video stream is viewed it works for a few frames then the phone is disconnected. STF complains of lost connection to minicap.

When trying minicap by itself it hangs and segfaults. output below.

output of minicap:

```
INFO: Using projection 1080x1920@1080x1920/0
INFO: (external/MY_minicap/src/minicap_22.cpp:240) Creating SurfaceComposerClient
INFO: (external/MY_minicap/src/minicap_22.cpp:243) Performing SurfaceComposerClient init check
INFO: (external/MY_minicap/src/minicap_22.cpp:250) Creating virtual display
INFO: (external/MY_minicap/src/minicap_22.cpp:256) Creating buffer queue
INFO: (external/MY_minicap/src/minicap_22.cpp:261) Creating CPU consumer
INFO: (external/MY_minicap/src/minicap_22.cpp:265) Creating frame waiter
INFO: (external/MY_minicap/src/minicap_22.cpp:269) Publishing virtual display
INFO: (jni/minicap/JpgEncoder.cpp:64) Allocating 6268932 bytes for JPG encoder
INFO: (jni/minicap/minicap.cpp:444) New client connection
Segmentation fault
```

If no connection is made; the output of minicap stops and, even after waiting a considerable amount of time, no OK is printed.

We have also tested against Samsung S4 and Oneplus One. Both of these function flawlessly. So it is just the S5 Neo that is causing us issues.

**Comment by sorccu** [comment]
If you're a business, consider becoming a [hardware sponsor](https://github.com/openstf/stf#sponsors-wanted) and send us the device. Otherwise there are some things we can try to check remotely, but it's very time consuming.

**Comment by Trugath** [comment]
After streaming a few times the phone soft bricks and is only restart-able by removing the battery.

I reduced the projection from  1080x1920@1080x1920/0 to  1080x1920@540x960/0 and it is a lot more stable. It doesn't segfault immediately on connection when manually launched (it has seg faulted once)

STF runs somewhat more stable with a half(quarter?) projection.

I am guessing the seg faults and disconnections are from the overly-aggressive Samsung background app killer shooting minicap in the head for memory usage.

**Comment by Trugath** [comment]
I reduced the projection from  1080x1920@1080x1920/0 to  1080x1920@540x960/0 and it is a lot more stable. It doesn't segfault immediately on connection when manually launched (it has seg faulted once)

STF runs somewhat more stable with a half(quarter?) projection.

I am guessing the seg faults and disconnections are from the overly-aggressive Samsung background app killer shooting minicap in the head for memory usage.

**Comment by sorccu** [comment]
If you have NDK installed and can build minicap, try running this :

```bash
adb logcat | ndk-stack -sym obj/local/arm64-v8a
```

It should show a bit more details about where the error occurs.

**Comment by sorccu** [comment]
Alternatively if you happen to be proficient with `gdb`, I can give you instructions to make it work.

**Comment by vbanthia** [comment]
Having same problem with my Samsung Galaxy A7 (2016) Device. 

Below is the device info.

```js
manufacturer: 'SAMSUNG',
model: 'SM-A710F',
version: '5.1.1',
abi: 'armeabi-v7a',
sdk: '22',
product: 'a7xeltexx',
display:
 { id: 0,
   width: 1080,
   height: 1920,
   xdpi: 403.4110107421875,
   ydpi: 403.0409851074219,
   fps: 59,
   density: 3
}
```

I read source code and found some [comments](https://github.com/openstf/minicap/blob/master/jni/minicap-shared/aosp/include/Minicap.hpp#L110-L122) regarding Samsung devices. 

>  // Set the display's real information. This cannot be accessed automatically
  // due to manufacturers (mainly Samsung) having customized
  // android::DisplayInfo. The information has to be gathered somehow and then
  // passed on here. Currently only the following properties are actually
  // used: width and height.
  virtual int
  setRealInfo(const DisplayInfo& info) = 0;
};

>// Attempt to get information about the given display. This may segfault
// on some devices due to manufacturer (mainly Samsung) customizations.
int
minicap_try_get_display_info(int32_t displayId, Minicap::DisplayInfo* info);

I tried various permutation of display_info, but no success.

Can you provide some instructions how to debug this using `gdb`? Below is my `adb logcat` result when it crashes.

```sh
********** Crash dump: **********
Build fingerprint: 'samsung/a7xeltexx/a7xelte:5.1.1/LMY47X/A710FXXU1APAC:user/release-keys'
pid: 19466, tid: 19468, name: Binder_2  >>> /data/local/tmp/minicap-devel/minicap <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Stack frame #00 pc 00004214  /system/lib/libcutils.so (android_atomic_add+16)
Stack frame #01 pc 0000edc7  /system/lib/libutils.so (android::RefBase::decStrong(void const*) const+10)
Stack frame #02 pc 00029efb  /system/lib/libgui.so (android::sp<android::IBinder>::~sp()+18)
Stack frame #03 pc 00030069  /system/lib/libgui.so (android::ConsumerBase::onFrameReplaced(android::BufferItem const&)+68)
Stack frame #04 pc 0002bb39  /system/lib/libgui.so (android::BufferQueue::ProxyConsumerListener::onFrameReplaced(android::BufferItem const&)+26)
Stack frame #05 pc 0002f157  /system/lib/libgui.so (android::BufferQueueProducer::queueBuffer(int, android::IGraphicBufferProducer::QueueBufferInput const&, android::IGraphicBufferProducer::QueueBufferOutput*)+590)
Stack frame #06 pc 000346c7  /system/lib/libgui.so (android::BnGraphicBufferProducer::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+626)
Stack frame #07 pc 0001a8b5  /system/lib/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+60)
Stack frame #08 pc 0001f963  /system/lib/libbinder.so (android::IPCThreadState::executeCommand(int)+582)
Stack frame #09 pc 0001fa87  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+38)
Stack frame #10 pc 0001fac9  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+48)
Stack frame #11 pc 00023c63  /system/lib/libbinder.so
Stack frame #12 pc 000106a9  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+112)
Stack frame #13 pc 00010219  /system/lib/libutils.so
Stack frame #14 pc 000174a7  /system/lib/libc.so (__pthread_start(void*)+30)
Stack frame #15 pc 000154c3  /system/lib/libc.so (__start_thread+6)
```

**Comment by vbanthia** [comment]
And Also, my development environment is OS X right now with android ndk installed. I can build minicap but not shared libraries. In case if it is required to build shared libraries, I will setup that environment too knowing it will take forever.

**Comment by sorccu** [comment]
I have gdb set up in a branch, let me see if i can cherry-pick it.

**Comment by sorccu** [comment]
See https://github.com/openstf/minicap#debugging and the commit log. It's been almost one year since I last used it, but it worked OK.

**Comment by vbanthia** [comment]
Thanks, will try it :)

**Comment by sorccu** [comment]
There was some reason I didn't commit it earlier. I don't remember and didn't find any useful notes in the commit log, unfortunately. It's possible you may have to build the shared libraries with additional debug options to see all symbols. Otherwise you might not see the symbol names but it should still work. Or, maybe the gdb.setup file needed a little manual tweaking.

**Comment by sorccu** [comment]
I think I remember now. I was working on a version that didn't require the shared libs at all. It ended in a failure at the time, but only due to my limited knowledge of memory layouts and inner workings of C++ constructors/destructors. I still think it'd be possible with more research.

**Comment by vbanthia** [comment]
yeah, able to run gdb debugger now. There has been some changes in latest ndk version (r11c).

`gdbclient` path has been changed to `$NDK_ROOT/prebuilt/darwin-x86_64/bin/gdb` from `"$NDK_ROOT/toolchains/.../arm-linux-androideabi-gdb"`

Very minute, you have written `ndk.sh` instead of `gdb.sh` in the README. Will improve docs, once I understand these all clearly.

**Comment by sorccu** [comment]
Yeah, it worked with r10e (64-bit).

**Comment by rdegelo** [comment]
Hello I'm experiencing the same issue on Samsung Galaxy A5

Is there any way to fix it?

**Comment by sorccu** [comment]
Donate a device (used is fine) or the money to buy that device, otherwise we can't do anything. Please see https://salt.bountysource.com/teams/openstf if you're interested.

**Comment by ledinhphuong** [comment]
Happening on my `Samsung Galaxy Note4`:

* Device information:
```
[ro.product.manufacturer]: [samsung]
[ro.product.model]: [SM-N910C]
[ro.build.version.release]: [5.1.1]
[ro.product.cpu.abi2]: [armeabi]
[ro.product.cpu.abi]: [armeabi-v7a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.build.version.sdk]: [22]
```

* Environment information:
```
Mac OSX 10.11.6
Android NDK: r11c
```


I try to get more logs in the device much as I can by running `./run.sh autosize` command:
```
I/DEBUG   ( 9573): Build fingerprint: 'samsung/treltexx/trelte:5.1.1/LMY47X/N910CXXS2CPD3:user/release-keys'
I/DEBUG   ( 9573): Revision: '21'
W/NativeCrashListener( 3484): Couldn't find ProcessRecord for pid 23417
I/DEBUG   ( 9573): ABI: 'arm'
I/DEBUG   ( 9573): pid: 23417, tid: 23418, name: Binder_1  >>> /data/local/tmp/minicap-devel/minicap <<<
E/DEBUG   ( 9573): AM write failure (32 / Broken pipe)
I/DEBUG   ( 9573): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
I/DEBUG   ( 9573):     r0 ffffffff  r1 00000000  r2 b6f2ed54  r3 b643b2e0
I/DEBUG   ( 9573):     r4 00000000  r5 ffffffff  r6 b6301674  r7 b63016dc
I/DEBUG   ( 9573):     r8 00000001  r9 b6301720  sl b6301738  fp b64741f4
I/DEBUG   ( 9573):     ip b6e5fd60  sp b6301648  lr b6e57214  pc b6e57214  cpsr 400f0010
I/DEBUG   ( 9573):
I/DEBUG   ( 9573): backtrace:
I/DEBUG   ( 9573):     #00 pc 00004214  /system/lib/libcutils.so (android_atomic_add+16)
I/DEBUG   ( 9573):     #01 pc 0000edc7  /system/lib/libutils.so (android::RefBase::decStrong(void const*) const+10)
I/DEBUG   ( 9573):     #02 pc 00029f1b  /system/lib/libgui.so (android::sp<android::IBinder>::~sp()+18)
I/DEBUG   ( 9573):     #03 pc 00030021  /system/lib/libgui.so (android::ConsumerBase::onFrameReplaced(android::BufferItem const&)+68)
I/DEBUG   ( 9573):     #04 pc 0002bad1  /system/lib/libgui.so (android::BufferQueue::ProxyConsumerListener::onFrameReplaced(android::BufferItem const&)+26)
I/DEBUG   ( 9573):     #05 pc 0002f137  /system/lib/libgui.so (android::BufferQueueProducer::queueBuffer(int, android::IGraphicBufferProducer::QueueBufferInput const&, android::IGraphicBufferProducer::QueueBufferOutput*)+574)
I/DEBUG   ( 9573):     #06 pc 000345b5  /system/lib/libgui.so (android::BnGraphicBufferProducer::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+628)
I/DEBUG   ( 9573):     #07 pc 0001a8f5  /system/lib/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+60)
I/DEBUG   ( 9573):     #08 pc 0001f9db  /system/lib/libbinder.so (android::IPCThreadState::executeCommand(int)+582)
I/DEBUG   ( 9573):     #09 pc 0001faff  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+38)
I/DEBUG   ( 9573):     #10 pc 0001fb41  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+48)
I/DEBUG   ( 9573):     #11 pc 00023cdf  /system/lib/libbinder.so
I/DEBUG   ( 9573):     #12 pc 000106a9  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+112)
I/DEBUG   ( 9573):     #13 pc 00010219  /system/lib/libutils.so
I/DEBUG   ( 9573):     #14 pc 000174a7  /system/lib/libc.so (__pthread_start(void*)+30)
I/DEBUG   ( 9573):     #15 pc 000154c3  /system/lib/libc.so (__start_thread+6)
I/DEBUG   ( 9573):
I/DEBUG   ( 9573): Tombstone written to: /data/tombstones/tombstone_09
E/        ( 9573): ro.product_ship = true
E/        ( 9573): ro.debug_level = 0x4f4c
E/audit   ( 4751): type=1701 msg=audit(1473332067.288:1259): auid=4294967295 uid=2000 gid=2000 ses=4294967295 subj=u:r:shell:s0 pid=23418 comm="Binder_1" reason="memory violation" sig=11
I/BootReceiver( 3484): Copying /data/tombstones/tombstone_09 to DropBox (SYSTEM_TOMBSTONE)
E/Surface ( 2863): queueBuffer: error queuing buffer to SurfaceTexture, -32
E/SurfaceFlinger( 2863): eglSwapBuffers(0x1, 0xb0854480) failed with 0x0000300b
W/libEGL  ( 2863): EGLNativeWindowType 0xb44b2808 disconnect failed
E/VirtualDisplaySurface( 2863): VirtualDisplaySurface is deleted,WFDMode 0
V/BroadcastQueue( 3484): [background] Process cur broadcast BroadcastRecord{1718b310 u0 android.intent.action.DROPBOX_ENTRY_ADDED} DELIVERED for app ProcessRecord{15a704d8 11772:com.samsung.android.sm/1000}
V/BroadcastQueue( 3484): [background] Process cur broadcast BroadcastRecord{1718b310 u0 android.intent.action.DROPBOX_ENTRY_ADDED} DELIVERED for app ProcessRecord{f064300 7831:com.google.android.gms/u0a14}
D/CrashAnrDetector( 3484): Build: samsung/treltexx/trelte:5.1.1/LMY47X/N910CXXS2CPD3:user/release-keys
D/CrashAnrDetector( 3484): Hardware: universal5433
D/CrashAnrDetector( 3484): Revision: 21
D/CrashAnrDetector( 3484): Bootloader: N910CXXS2CPD3
D/CrashAnrDetector( 3484): Radio: unknown
D/CrashAnrDetector( 3484): Kernel: Linux version 3.10.9-6035384 (dpi@SWHD4306) (gcc version 4.8 (GCC) ) #1 SMP PREEMPT Tue Apr 5 22:21:20 KST 2016
```

Also, I try to reduce the [output resolution](https://github.com/openstf/minicap/blob/master/run.sh#L30) but it still happens smaller:
```diff
-args="-P $size@$size/0"
+args="-P $size@320x320/0"
```

**Comment by vbanthia** [comment]
Looks like this is only happening in Android 5.1.1 for some Samsung devices.

**Comment by dkw72n** [comment]
I happened to have a `Samsung Galaxy Note4`, and spent my last weekend on this issue.
I got a conclusion, but it's kind of disappointing.
The device is flashed with a `5.1.1` stock rom, which can be told from the crash log.
Here is the crash log:
```
--------- beginning of main
I/DEBUG   ( 2870): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   ( 2870): Build fingerprint: 'samsung/trhpltexx/trhplte:5.1.1/LMY47X/N910UXXU2COJ2:user/release-keys'
I/DEBUG   ( 2870): Revision: '13'
I/DEBUG   ( 2870): ABI: 'arm'
I/DEBUG   ( 2870): pid: 8834, tid: 12756, name: Binder_3  >>> /data/local/tmp/minicap <<<
I/DEBUG   ( 2870): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
I/DEBUG   ( 2870):     r0 ffffffff  r1 00000000  r2 b6f00d54  r3 b603b2e0
I/DEBUG   ( 2870):     r4 00000000  r5 ffffffff  r6 b5bff674  r7 b5bff6dc
I/DEBUG   ( 2870):     r8 00000001  r9 b5bff720  sl b5bff738  fp b60741f4
I/DEBUG   ( 2870):     ip b6e31d64  sp b5bff648  lr b6e2a1cc  pc b6e2a1cc  cpsr 400b0010
I/DEBUG   ( 2870):
I/DEBUG   ( 2870): backtrace:
I/DEBUG   ( 2870):     #00 pc 000041cc  /system/lib/libcutils.so (android_atomic_add+16)
I/DEBUG   ( 2870):     #01 pc 0000edc7  /system/lib/libutils.so (android::RefBase::decStrong(void const*) const+10)
I/DEBUG   ( 2870):     #02 pc 00029dcb  /system/lib/libgui.so (android::sp<android::IBinder>::~sp()+18)
I/DEBUG   ( 2870):     #03 pc 0002fe49  /system/lib/libgui.so (android::ConsumerBase::onFrameReplaced(android::BufferItem const&)+68)
I/DEBUG   ( 2870):     #04 pc 0002b97d  /system/lib/libgui.so (android::BufferQueue::ProxyConsumerListener::onFrameReplaced(android::BufferItem const&)+26)
I/DEBUG   ( 2870):     #05 pc 0002ef5f  /system/lib/libgui.so (android::BufferQueueProducer::queueBuffer(int, android::IGraphicBufferProducer::QueueBufferInput const&, android::IGraphicBufferProducer::QueueBufferOutput*)+574)
I/DEBUG   ( 2870):     #06 pc 000343cb  /system/lib/libgui.so (android::BnGraphicBufferProducer::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+610)
I/DEBUG   ( 2870):     #07 pc 0001a8b5  /system/lib/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+60)
I/DEBUG   ( 2870):     #08 pc 0001f963  /system/lib/libbinder.so (android::IPCThreadState::executeCommand(int)+582)
I/DEBUG   ( 2870):     #09 pc 0001fa87  /system/lib/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+38)
I/DEBUG   ( 2870):     #10 pc 0001fac9  /system/lib/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+48)
I/DEBUG   ( 2870):     #11 pc 00023c67  /system/lib/libbinder.so
I/DEBUG   ( 2870):     #12 pc 000106a9  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+112)
I/DEBUG   ( 2870):     #13 pc 00010219  /system/lib/libutils.so
I/DEBUG   ( 2870):     #14 pc 000174a7  /system/lib/libc.so (__pthread_start(void*)+30)
I/DEBUG   ( 2870):     #15 pc 000154c3  /system/lib/libc.so (__start_thread+6)
I/DEBUG   ( 2870):
I/DEBUG   ( 2870): Tombstone written to: /data/tombstones/tombstone_0
```
The reason it crashed is that the vtable of `android::ConsumerBase::FrameAvailableListener` in samsung is not agreed with the one in minicap. After the first frame arrived(in `frame #03` above), instead of `onFrameAvailable`, the `dtor` is called. 
Sadly I failed to find a decent solution to this issue.

Hope it helps.

**Comment by sorccu** [comment]
Thanks, that's very useful information. It seems that it only happens on the 5.1.1 firmware, as practically all reports are from that version. Reports say the devices work after upgrading to 6.0.

I'm fairly confident we can find a workaround once I have a little time to look into it.

**Comment by sorccu** [comment]
@dkw72n and others Please consider joining our slack at https://openstf.slack.com/ :) Send me an email at simo @ {name of this github organization} .io and I'll invite you.

**Comment by dkw72n** [comment]
@sorccu 
[libgui.zip](https://github.com/openstf/minicap/files/577437/libgui.zip)
Attached is the libgui.so pulled from my device.

**Comment by sorccu** [comment]
Actually I do see the `onFrameReplaced` method in the 5.1 source tree. So does the stack trace mean that it tried to call onFrameReplaced, but accidentally called the destructor instead?

**Comment by dkw72n** [comment]
Not exactly, there are two steps actually:
a. it tries to call `onFrameReplaced`, but call the `dtor` instead, this call returns without error.
b. right after step a, it tries to decrease the reference count on the accidentally freed object.

step b is what you saw in the stack trace, step a is the root cause.

**Comment by sorccu** [comment]
These Samsung devices on 5.1.x should now work thanks to @dkw72n :)

**Comment by ledinhphuong** [comment]
@sorccu @dkw72n I verified with the latest [code](https://github.com/openstf/minicap/commit/4851a9919b9a3a310326a86b7bfead9dd57c2cb4). So it still happens on my `Samsung Galaxy Note4` device.

**Comment by sorccu** [comment]
If you installed from source, did you remember to run `npm install`?

**Comment by ledinhphuong** [comment]
@sorccu I run minicap directly by `./run.sh autosize -t` command.

**Comment by dkw72n** [comment]
@ledinhphuong Appreciate if you could post the call stack and the `/system/lib/libgui.so` from your device.

**Comment by ledinhphuong** [comment]
@sorccu @dkw72n I tried to remove node_modules folder (in STF project) and run `npm install` again. So the issue is fixed on my device. Thanks.

P.s: Here are `npm ls` of STF project
[stf-node-modules.txt](https://github.com/openstf/minicap/files/593888/stf-node-modules.txt)

**Comment by sorccu** [comment]
That's great, thanks for the update!

If you want to use minicap master in stf, you can do as follows.

First, in the minicap repo:

```
npm link
```

(it should also run `make`, but if it doesn't, run it manually)

Then, it the stf repo:

```
npm link minicap-prebuilt
```

Now it should be linked to your local minicap.
